### ISSUE TITLE
test DepthTrack dataset error : unable to connect to tracker

### ISSUE THREAD

**Issue by 923714892** [jiawen-zhu/ViPT#1]
Thank you for your contribution, VIPT is a very good article.
When i try to test DepthTrack dataset , Some errors have occurred.
Unable to connect to tracker.
And the log shown : No module named vipt_baseline.
I want to know how can i solve this error.

**Comment by handsomeDanny** [comment]
Did you finish the test on depthtrack dataset? i have some problem when testing vipt on depthtrack. i use the command 'vot test vipt_deep' ,and get error 'vot.dataset.DatasetException: Frame does not have information for channel: depth'. when using command 'vot evaluate --workspace ./ vipt_deep', the error is 'vot.workspace.WorkspaceException: Experiment stack does not exist'.could you please tell me how to solve this error?

**Comment by jiawen-zhu** [comment]
> Thank you for your contribution, VIPT is a very good article. When i try to test DepthTrack dataset , Some errors have occurred. Unable to connect to tracker. And the log shown : No module named vipt_baseline. I want to know how can i solve this error.

Hi~, we've tested the relevant parts and it's all right, the problem seems to be due to not configuring the VOT test tool properly, you can check the workspace path, tracker name in .ini file, etc.

**Comment by tdd233** [comment]
> 您是否完成了深度跟踪数据集的测试？我在深度跟踪上测试 VIP 时遇到了一些问题。我使用命令“vot test vipt_deep”，并得到错误“vot.dataset.DatasetException：帧没有通道：深度”的信息。使用命令“vot evaluate --workspace ./ vipt_deep”时，错误为“vot.workspace.WorkspaceException：实验堆栈不存在”。你能告诉我如何解决这个错误吗？

Hi, I met the same error. Have you solved the problem? Could you please offer some help? Thanks a lot.
