### ISSUE TITLE
lasher tracking results

### ISSUE THREAD

**Issue by handsomeDanny** [jiawen-zhu/ViPT#10]
thanks for your wonderful job. recently, i'm doing some works on RGBT tracking, and i've noticed that there are two stages(937 234) on the rgbt traing log you provided, it seems like that you used two kind of total batch size(64,256) which is differernt in your paper, and which result did you choose?
by the way, could you please provide other tracker's(protrack, ostrack,transt...) tracking results on lasher?
thanks a lot.

**Comment by laisimiao** [comment]
That's the log re-add trace, in our paper results, we just use bs=32.
you can use our orgnized lasher toolkit which inlcudes other results that are in our paper: https://drive.google.com/file/d/107okp7X5ClAzBXmkNpUSlkbFYNAdezku/view?usp=drive_link
