### ISSUE TITLE
test DepthTrack dataset error

### ISSUE THREAD

**Issue by tdd233** [jiawen-zhu/ViPT#12]
Hi, I'm very interested in your outstanding work and try to reproduce it. When I test on DepthTrack dataset following your instructions, an error occurred "vot.workspace.WorkspaceException: Experiment stack does not exist". I find that issue#2 described the same problem so I try to specify the stack_file(votrbd2021.yaml) path just like what he did, but there is no votrgbd2021.yaml file in the vot-toolkit.

**Comment by tdd233** [comment]
Now I use vot2021/rgbd.yaml as stack file, it seems that the above error has been solved. But a new error occurred "AttributeError: 'SingleObject' object has no attribute '__name__'". I also tried "vot test" to check the error, and it showed that "Unable to continue without a tracker". Could you please offer some help? Thanks a lot.
![image](https://github.com/jiawen-zhu/ViPT/assets/93235196/d9e9e025-e644-4ad7-b869-64cd5d01754d)

**Comment by laisimiao** [comment]
@tdd233 please use the vot-toolkit==0.5.3 and re-try it.
