### ISSUE TITLE
candidate elimination‘s reference 

### ISSUE THREAD

**Issue by RizhaoCai** [jiawen-zhu/ViPT#13]
candidate elimination 的reference 有吗？

class VisionTransformerCE(VisionTransformer):
    """ Vision Transformer with candidate elimination (CE) module

    A PyTorch impl of : `An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale`
        - https://arxiv.org/abs/2010.11929

    Includes distillation token & head support for `DeiT: Data-efficient Image Transformers`
        - https://arxiv.org/abs/2012.12877
    """

但是我在Paper中没有看到这个candidate elimination的讨论

**Comment by jiawen-zhu** [comment]
你好，candidate elimination是OSTrack中的模块，参考OSTrack原文即可。
