### ISSUE TITLE
error happens when running 'vot evaluate --workspace ./ vipt_deep'

### ISSUE THREAD

**Issue by handsomeDanny** [jiawen-zhu/ViPT#2]
Thanks for your excellent work. 
When I try to test ViPT on depthtrack dataset using vot-toolkit, error occured.
error 'vot.workspace.WorkspaceException: Experiment stack does not exist' happened when running 'vot evaluate --workspace ./ vipt_deep',
Could you please tell me how to solve this error?

**Comment by jiawen-zhu** [comment]
The problem looks like you did not install or successfully install vot-toolkit.

**Comment by handsomeDanny** [comment]
Thanks for your reply. I'v already solved this error.
I found the reason is that there is not votrgbd2021.yaml file in the sequences directory, so that got stack_file==None.
And I'v successfully evaluated ViPT on depthtrack, I've trained the model for 30 epoch with the initial deep_rgbd.yaml. (because I found that the total loss hovered around 0.72 when epoch > 30)
Got the results pr(0.557) re(0.560) f(0.559)
Will I get result more similar to （0.592 0.596 0.594）in paper as I continue training the model with any changes?

**Comment by jiawen-zhu** [comment]
Yeah, similar results will be gained if maintaining a similar experimental setup as in our paper.

**Comment by handsomeDanny** [comment]
OK, thanks a lot.
By the way, would you mind to provide the training log files?

**Comment by jiawen-zhu** [comment]
No problem, the training logs have been uploaded.
Thanks for your attention in our work~

**Comment by Jack-lam1** [comment]
> Thanks for your reply. I'v already solved this error. I found the reason is that there is not votrgbd2021.yaml file in the sequences directory, so that got stack_file==None. And I'v successfully evaluated ViPT on depthtrack, I've trained the model for 30 epoch with the initial deep_rgbd.yaml. (because I found that the total loss hovered around 0.72 when epoch > 30) Got the results pr(0.557) re(0.560) f(0.559) Will I get result more similar to （0.592 0.596 0.594）in paper as I continue training the model with any changes?

hey, I have the same error. Could you please send me the votrgbd2021.yaml？

**Comment by handsomeDanny** [comment]
> > Thanks for your reply. I'v already solved this error. I found the reason is that there is not votrgbd2021.yaml file in the sequences directory, so that got stack_file==None. And I'v successfully evaluated ViPT on depthtrack, I've trained the model for 30 epoch with the initial deep_rgbd.yaml. (because I found that the total loss hovered around 0.72 when epoch > 30) Got the results pr(0.557) re(0.560) f(0.559) Will I get result more similar to （0.592 0.596 0.594）in paper as I continue training the model with any changes?
> 
> hey, I have the same error. Could you please send me the votrgbd2021.yaml？
you can get yaml files on https://github.com/votchallenge/toolkit/tree/master/vot/stack. and I just specify the file path(stack_file) at anaconda\envs\depth38\Lib\site-packages\vot_toolkit-0.5.3-py3.8.egg\vot\workspace\__init__.py line 34. I wish it can help you.

**Comment by handsomeDanny** [comment]
> > Thanks for your reply. I'v already solved this error. I found the reason is that there is not votrgbd2021.yaml file in the sequences directory, so that got stack_file==None. And I'v successfully evaluated ViPT on depthtrack, I've trained the model for 30 epoch with the initial deep_rgbd.yaml. (because I found that the total loss hovered around 0.72 when epoch > 30) Got the results pr(0.557) re(0.560) f(0.559) Will I get result more similar to （0.592 0.596 0.594）in paper as I continue training the model with any changes?
> 
> hey, I have the same error. Could you please send me the votrgbd2021.yaml？

you can get yaml files on https://github.com/votchallenge/toolkit/tree/master/vot/stack. and I just specify the file path(stack_file) at anaconda\envs\depth38\Lib\site-packages\vot_toolkit-0.5.3-py3.8.egg\vot\workspace\__init__.py line 34. I wish it can help you.

**Comment by tdd233** [comment]
> 

Hi, I met the same problem. And when I specify the file path(stack_file), a new error occured:
![Uploading 1685434419059.png…]()
Have you met this erorr?

**Comment by tdd233** [comment]
> > > 
> > 
> > 
> > Hi, I met the same problem. And when I specify the file path(stack_file), a new error occured: ![1685434419059](https://user-images.githubusercontent.com/93235196/241893014-b031c89c-5fa8-4275-a440-2832264c1b54.png)
> > Have you met this erorr?
> 
> i have not met this error, maybe you can try this, put stack_file in Depthtrack_workspace without specifying it, like ViPT/Depthtrack_workspace/votrgbd2021.yaml.

Thanks for your reply. Unfortunately, I tried it but the error still exists. :(

**Comment by laisimiao** [comment]
@tdd233 please use the vot-toolkit==0.5.3, nowadays it has been updated for VOTS2023 challenge if you install the latest version.
