### ISSUE TITLE
VisEvent Data spec file

### ISSUE THREAD

**Issue by Zongwei97** [jiawen-zhu/ViPT#21]
Hello,

Thanks for the great work.
Would it be possible to provide the train/val split for visevent dataset?

I can only find the train/val split for depthtrack and lasher, but not for visevent.
Or does it mean that the model is trained with full visevent without val?

Thanks

**Comment by laisimiao** [comment]
@Zongwei97 we train the model of RGB-E modalities on its train split without val

**Comment by Zongwei97** [comment]
Thanks for the reply!
