### ISSUE TITLE
can‘t open/read file: check file path/integrity

### ISSUE THREAD

**Issue by dddqy** [jiawen-zhu/ViPT#3]
Thank you for your work. 
When I want to train the model using LasHeR dataset, some errors happen.
[ WARN:0@8.731] global loadsave.cpp:244 findDecoder imread_('./LasHeR/TrainingSet/trainingset/girlwithredhat/visible/000131.jpg'): can't open/read file: check file path/integrity
It seems that the sampled frames cannot be successfully read though I have checked the data path.
I notice that you mentioned '# Note original filename is chaotic, we rename them' in your code.
Is there any problem with the filename? 
Would you please tell me how can I solve this problem?
Thank you so much again.

**Comment by dddqy** [comment]
Thanks for your reply! As you say, this error is caused by the chaotic names of the video frames. And I have solved it by writing a script to rename the sequences in the training set. Thank you so much.

**Comment by lx-ynu** [comment]
> Thanks for your reply! As you say, this error is caused by the chaotic names of the video frames. And I have solved it by writing a script to rename the sequences in the training set. Thank you so much.

Hi, I have the same problem when using LasHeR dataset, how did you solve it and can you provide your script? Thanks very much.

**Comment by Hrren** [comment]
Hello, I have encountered the same problem. May I know how it was resolved
