### ISSUE TITLE
FFT code in the paper

### ISSUE THREAD

**Issue by Tianlu-Zhang** [jiawen-zhu/ViPT#8]
Thanks for your interesting work. I noticed that in the 4.4 Exploration Studies of the paper, the proposed ViPT was also compared with a FFT tracker, which can achived the SR score of 51.7. But in my implementation, I have got a much lower score. So could you please offer the source code or such a FFT tracker in the paper? Thanks very much for your help.

**Comment by laisimiao** [comment]
@Tianlu-Zhang Refer to https://github.com/xiaozai/DeT, like DeT_DiMP50 vs. DiMP50
