### ISSUE TITLE
Query about trainable parameters initialization

### ISSUE THREAD

**Issue by qjyn** [jiawen-zhu/ViPT#9]
Thanks for your interesting work. As mentioned in the experimental settings of the paper, the trainable prompt learning parameters are initialized with xavier uniform initialization scheme. Where is the code that initializes the trainable parameters?
If you can reply my queries, I would appreciate it very much.

**Comment by LiShenglana** [comment]
> Thanks for your interesting work. As mentioned in the experimental settings of the paper, the trainable prompt learning parameters are initialized with xavier uniform initialization scheme. Where is the code that initializes the trainable parameters? If you can reply my queries, I would appreciate it very much.

Did you solve this problem, I had the same problem as you, I didn't find the setting in the code for the trainable parameter. Looking forward to hearing from you, thanks.

**Comment by qjyn** [comment]
The function get_optimizer_scheduler located in lib/train/base_functions.py determines which parameters are trainable. Hope this helps.
The function get_optimizer_scheduler located in lib/train/base_functions.py determines which parameters are trainable. Hope this helps.

王弘宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiawen-zhu/ViPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月16日(星期六) 上午10:28
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [jiawen-zhu/ViPT] Query about trainable parameters initialization (Issue #9)





  
Thanks for your interesting work. As mentioned in the experimental settings of the paper, the trainable prompt learning parameters are initialized with xavier uniform initialization scheme. Where is the code that initializes the trainable parameters? If you can reply my queries, I would appreciate it very much.
  
Did you solve this problem, I had the same problem as you, I didn't find the setting in the code for the trainable parameter. Looking forward to hearing from you, thanks.

**Comment by LiShenglana** [comment]
> The function get_optimizer_scheduler located in lib/train/base_functions.py determines which parameters are trainable. Hope this helps.

It helps! Thanks for your reply. I hope you have a wonderful day!
